### ISSUE TITLE
Issue with lightlslider plugin

### ISSUE THREAD

**Issue by nickbe** [Sommerregen/grav-plugin-external-links#1]
The external link plugin seems to disrupt the lightslider plugin. After removin your plugin the lightslider worked again as expected.

We tried to confirm this problem in various scenarios and it does that every time. Could you please look into this? There's also a very recent grav forum thread about this.

**Comment by nickbe** [comment]
Didn't mean to close it. Tapped on the wrong button while talking on the phone _me stupid_

**Comment by rhukster** [comment]
Forum thread mentioned: http://getgrav.org/forum#!/general:lightslider-stopped-working

**Comment by Sommerregen** [comment]
Hi @nickbe and @rhukster,

thanks for pointing it out. The issue will be fixed in the next release **External Links 1.1.2** I publish today.
