### ISSUE TITLE
Preferences Not Showing

### ISSUE THREAD

**Issue by ghost** [Sommerregen/grav-plugin-external-links#13]
FYI ... I just wanted to report that the Preferences are not showing on Page Options tab under GRAV Beta. THX!

**Comment by Sommerregen** [comment]
Hi @umbergerba I will investigate this. This is most likely due to the change of how blueprints are loaded in the current betas of **Admin panel**. Thus, replacing line [117](https://github.com/Sommerregen/grav-plugin-external-links/blob/master/external_links.php#L117) with

``` php
if ($blueprint->get('form/fields/tabs', null, '/')) {
 ...
}
```

will fix the error.
