### ISSUE TITLE
rel="noopener noreferrer"

### ISSUE THREAD

**Issue by MarkBaillieDev** [Sommerregen/grav-plugin-external-links#21]
Could we please add (by default or via option) rel="noopener noreferrer" to the external links ?

https://medium.com/@jitbit/target-blank-the-most-underestimated-vulnerability-ever-96e328301f4c

**Comment by Sommerregen** [comment]
Hi @markbaillie ,

good resource and thanks for reminding me! 👍  I stumbled on the same website a while ago, but forgot to update the plugin. You can find the latest changes in the develop branch. I want to tackle another feature request before releasing the next version first.

**Comment by Sommerregen** [comment]
Merged and release.
