### ISSUE TITLE
Validation failed: title is not defined in blueprints

### ISSUE THREAD

**Issue by jpfleury** [Sommerregen/grav-plugin-external-links#6]
Config: Grav 0.9.39 and External Links 1.3.0

I can't save changes in the plugin settings (url `/admin/plugins/external_links`). I always have an error (even if I don't change anything but only click the button _Save_):

> **Validation failed:** title is not defined in blueprints

![capture d ecran_2015-08-28_12-23-55](https://cloud.githubusercontent.com/assets/687082/9551528/b8b055d8-4d7f-11e5-9a20-da981396d47d.png)

**Comment by jpfleury** [comment]
Maybe it's a bug with the admin plugin?

**Comment by jpfleury** [comment]
According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

**Comment by Sommerregen** [comment]
Hi @jpfleury ,

yep, there are some options missing in the `blueprints.yaml` I'm aware of. This will be fixed in the next release. Thanks!
